/**
 * Mango API
 * This is the Mango API Server RESTful service for OpenAPI 3.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: haighis@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Install audit object
 */
export interface Install { 
    id?: string;
    name?: string;
    uri?: string;
    code?: string;
    version?: string;
    created?: string;
    kind?: string;
    namespace?: string;
    status?: boolean;
}

