/**
 * Mango API
 * This is the Mango API Server RESTful service for OpenAPI 3.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: haighis@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Item Dto object
 */
export interface ItemDto { 
    name?: string;
    description?: string;
    status?: string;
    url?: string;
    version?: string;
    namespace?: string;
}

