/**
 * Mango API
 * This is the Mango API Server RESTful service for OpenAPI 3.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: haighis@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Shell Type object
 */
export interface ShellType { 
    /**
     * Classification of the Shell Type.
     */
    classification: string;
    /**
     * Sub Classification of the Shell Type.
     */
    subClassification: string;
    /**
     * Description fo the Store Item.
     */
    description: string;
    id?: string;
}

